
# Replace the "❯" symbol in the prompt with "➜"
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[](green)"
error_symbol = "[](red)"
vicmd_symbol = "[](blue)"

[cmd_duration]
format = "󰔚 [$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"


