#!/bin/sh

#░█▀▀▄░█░▒█░▀█▀░▄▀▀▄░█▀▀░▀█▀░█▀▀▄░█▀▀▄░▀█▀
#▒█▄▄█░█░▒█░░█░░█░░█░▀▀▄░░█░░█▄▄█░█▄▄▀░░█░
#▒█░▒█░░▀▀▀░░▀░░░▀▀░░▀▀▀░░▀░░▀░░▀░▀░▀▀░░▀░
dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
riverctl spawn 'swaybg -m fill -i ~/pic/wallpaper/dark-hazy-forest.jpg'
riverctl spawn pipewire
riverctl spawn waybar
riverctl spawn mako
riverctl spawn 'foot --server'
# riverctl spawn yambar
# riverctl spawn kanshi
riverctl spawn 'nvim --headless "+Lazy! sync" +qa'
riverctl spawn 'chromium --disable-sync-preferences --no-startup-window'

#░▀█▀░█▀▀▄░▄▀▀▄░█░▒█░▀█▀
#░▒█░░█░▒█░█▄▄█░█░▒█░░█░
#░▄█▄░▀░░▀░█░░░░░▀▀▀░░▀░
riverctl keyboard-layout ch
riverctl set-repeat 60 350

#░▒█░▄▀░█▀▀░█░░█░█▀▀▄░░▀░░█▀▀▄░█▀▄
#░▒█▀▄░░█▀▀░█▄▄█░█▀▀▄░░█▀░█░▒█░█░█
#░▒█░▒█░▀▀▀░▄▄▄▀░▀▀▀▀░▀▀▀░▀░░▀░▀▀░
riverctl map normal Super Return spawn foot
riverctl map normal Super+Shift Return spawn 'foot --app-id=footsmall'
riverctl map normal Super Q close
riverctl map normal Super+Shift X exit
riverctl map normal Super P spawn 'grim -g "$(slurp)"'
riverctl map normal Super W spawn chromium
riverctl map normal Super+Shift W spawn 'chromium --incognito'
riverctl map normal Super F spawn 'foot -e yazi'
riverctl map normal Super+Shift F spawn 'foot --app-id=foot -e yazi'
riverctl map normal Super E spawn fuzzel
riverctl map normal Super Escape spawn 'wlogout --protocol layer-shell -b 4 -T 400 -B 400'

#░▒█▀▀▀█░█▀▄░█▀▀▄░█▀▀▄░▀█▀░█▀▄░█░░░░▄▀▀▄░█▀▀▄░█▀▄
#░░▀▀▀▄▄░█░░░█▄▄▀░█▄▄█░░█░░█░░░█▀▀█░█▄▄█░█▄▄█░█░█
#░▒█▄▄▄█░▀▀▀░▀░▀▀░▀░░▀░░▀░░▀▀▀░▀░░▀░█░░░░▀░░▀░▀▀░
scratch_tag=$((1 << 20))

riverctl map normal Super S toggle-focused-tags ${scratch_tag} # toggle the scratchpad
riverctl map normal Super+Shift S set-view-tags ${scratch_tag} # send windows to the scratchpad

# Set spawn tagmask to ensure new windows do not have the scratchpad tag unless explicitly set.
all_but_scratch_tag=$((((1 << 32) - 1) ^ $scratch_tag))
riverctl spawn-tagmask ${all_but_scratch_tag}

#░▒█░░▒█░░▀░░█▀▀▄░█▀▄░▄▀▀▄░█░░░█░░░▒█▀▄▀█░█▀▀▀░█▀▄▀█░▀█▀
#░▒█▒█▒█░░█▀░█░▒█░█░█░█░░█░▀▄█▄▀░░░▒█▒█▒█░█░▀▄░█░▀░█░░█░
#░▒▀▄▀▄▀░▀▀▀░▀░░▀░▀▀░░░▀▀░░░▀░▀░░░░▒█░░▒█░▀▀▀▀░▀░░▒▀░░▀░
# focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# swap the focused view with the next/previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# bump the focused view to the top of the layout stack
riverctl map normal Super+Shift A zoom

# decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# move views
riverctl map-pointer normal Super BTN_LEFT move-view

# resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

#░▒█░░░░█▀▀▄░█░░█░▄▀▀▄░█░▒█░▀█▀
#░▒█░░░░█▄▄█░█▄▄█░█░░█░█░▒█░░█░
#░▒█▄▄█░▀░░▀░▄▄▄▀░░▀▀░░░▀▀▀░░▀░
for i in $(seq 1 5); do
  tags=$((1 << ($i - 1)))
  riverctl map normal Super $i set-focused-tags $tags
  # tag focused view with tag [0-8]
  riverctl map normal Super+Shift $i set-view-tags $tags
  # toggle focus of tag [0-8]
  riverctl map normal Super+Control $i toggle-focused-tags $tags
  # toggle tag [0-8] of focused view
  riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# focus all tags / tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# toggle float
riverctl map normal Super Space toggle-float

# toggle fullscreen
riverctl map normal Super A toggle-fullscreen

# change layout orientation
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

# Set background and border color
riverctl background-color 0x1a1b26
riverctl border-color-focused 0xa6e3a1
riverctl border-color-unfocused 0x1a1b26

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float
riverctl rule-add -app-id 'footsmall' float
riverctl rule-add -app-id 'footsmall' dimensions 1100 800
riverctl focus-follows-cursor normal

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 8 -outer-padding 8 &
